project:
  type: website
  output-dir: docs

website:
  title: "ESS330 | SP25 | Daily Assignment 27 & 28"
  navbar:
    left:
      - href: index.qmd
        text: Daily Assignment 27 & 28

format:
  html:
    self-contained: true

editor: visual

